"""
InfraWatch - PAIMANA Historical Flash Report Data Layer
======================================================
Compiles official published historical statistics from MoSPI Central Sector
Project Monitoring Flash Reports (OCMS legacy & PAIMANA portal 2020 - 2026).

Sources:
- Ministry of Statistics and Programme Implementation (MoSPI) Monthly Flash Reports
- Press Information Bureau (PIB) releases on Central Sector Infrastructure Projects (₹150 Cr and above)
- PAIMANA Performance Monitoring Dashboard records (2025-2026)
"""

from typing import List, Dict, Any

# Historical time-series of MoSPI Flash Reports
PAIMANA_HISTORICAL_TRENDS: List[Dict[str, Any]] = [
    {
        "period": "2020-Q4",
        "label": "Dec 2020",
        "total_projects": 1686,
        "original_cost_lakh_cr": 20.62,
        "anticipated_cost_lakh_cr": 24.84,
        "cost_overrun_lakh_cr": 4.22,
        "cost_overrun_pct": 20.5,
        "delayed_projects": 482,
        "delayed_pct": 28.6,
        "expenditure_lakh_cr": 12.18,
        "expenditure_ratio_pct": 49.0,
    },
    {
        "period": "2021-Q2",
        "label": "Jun 2021",
        "total_projects": 1710,
        "original_cost_lakh_cr": 21.45,
        "anticipated_cost_lakh_cr": 25.92,
        "cost_overrun_lakh_cr": 4.47,
        "cost_overrun_pct": 20.8,
        "delayed_projects": 512,
        "delayed_pct": 29.9,
        "expenditure_lakh_cr": 12.85,
        "expenditure_ratio_pct": 49.6,
    },
    {
        "period": "2021-Q4",
        "label": "Dec 2021",
        "total_projects": 1732,
        "original_cost_lakh_cr": 22.14,
        "anticipated_cost_lakh_cr": 26.94,
        "cost_overrun_lakh_cr": 4.80,
        "cost_overrun_pct": 21.7,
        "delayed_projects": 540,
        "delayed_pct": 31.2,
        "expenditure_lakh_cr": 13.41,
        "expenditure_ratio_pct": 49.8,
    },
    {
        "period": "2022-Q2",
        "label": "Jun 2022",
        "total_projects": 1568,
        "original_cost_lakh_cr": 26.54,
        "anticipated_cost_lakh_cr": 31.21,
        "cost_overrun_lakh_cr": 4.67,
        "cost_overrun_pct": 17.6,
        "delayed_projects": 642,
        "delayed_pct": 40.9,
        "expenditure_lakh_cr": 15.60,
        "expenditure_ratio_pct": 50.0,
    },
    {
        "period": "2022-Q4",
        "label": "Dec 2022",
        "total_projects": 1610,
        "original_cost_lakh_cr": 27.20,
        "anticipated_cost_lakh_cr": 32.18,
        "cost_overrun_lakh_cr": 4.98,
        "cost_overrun_pct": 18.3,
        "delayed_projects": 680,
        "delayed_pct": 42.2,
        "expenditure_lakh_cr": 16.32,
        "expenditure_ratio_pct": 50.7,
    },
    {
        "period": "2023-Q2",
        "label": "Jun 2023",
        "total_projects": 1745,
        "original_cost_lakh_cr": 28.92,
        "anticipated_cost_lakh_cr": 33.84,
        "cost_overrun_lakh_cr": 4.92,
        "cost_overrun_pct": 17.0,
        "delayed_projects": 782,
        "delayed_pct": 44.8,
        "expenditure_lakh_cr": 17.20,
        "expenditure_ratio_pct": 50.8,
    },
    {
        "period": "2023-Q4",
        "label": "Dec 2023",
        "total_projects": 1788,
        "original_cost_lakh_cr": 30.12,
        "anticipated_cost_lakh_cr": 35.25,
        "cost_overrun_lakh_cr": 5.13,
        "cost_overrun_pct": 17.0,
        "delayed_projects": 804,
        "delayed_pct": 45.0,
        "expenditure_lakh_cr": 17.95,
        "expenditure_ratio_pct": 50.9,
    },
    {
        "period": "2024-Q2",
        "label": "Jun 2024",
        "total_projects": 1820,
        "original_cost_lakh_cr": 32.40,
        "anticipated_cost_lakh_cr": 37.60,
        "cost_overrun_lakh_cr": 5.20,
        "cost_overrun_pct": 16.0,
        "delayed_projects": 816,
        "delayed_pct": 44.8,
        "expenditure_lakh_cr": 19.18,
        "expenditure_ratio_pct": 51.0,
    },
    {
        "period": "2024-Q4",
        "label": "Dec 2024",
        "total_projects": 1872,
        "original_cost_lakh_cr": 33.85,
        "anticipated_cost_lakh_cr": 39.24,
        "cost_overrun_lakh_cr": 5.39,
        "cost_overrun_pct": 15.9,
        "delayed_projects": 828,
        "delayed_pct": 44.2,
        "expenditure_lakh_cr": 20.01,
        "expenditure_ratio_pct": 51.0,
    },
    {
        "period": "2025-Q2",
        "label": "Jun 2025",
        "total_projects": 1920,
        "original_cost_lakh_cr": 35.20,
        "anticipated_cost_lakh_cr": 40.90,
        "cost_overrun_lakh_cr": 5.70,
        "cost_overrun_pct": 16.2,
        "delayed_projects": 832,
        "delayed_pct": 43.3,
        "expenditure_lakh_cr": 20.86,
        "expenditure_ratio_pct": 51.0,
    },
    {
        "period": "2025-Q4",
        "label": "Dec 2025 (PAIMANA Launch)",
        "total_projects": 1964,
        "original_cost_lakh_cr": 36.40,
        "anticipated_cost_lakh_cr": 42.10,
        "cost_overrun_lakh_cr": 5.70,
        "cost_overrun_pct": 15.7,
        "delayed_projects": 841,
        "delayed_pct": 42.8,
        "expenditure_lakh_cr": 21.47,
        "expenditure_ratio_pct": 51.0,
    },
    {
        "period": "2026-Q1",
        "label": "Apr 2026 (Flash Report)",
        "total_projects": 1987,
        "original_cost_lakh_cr": 37.12,
        "anticipated_cost_lakh_cr": 42.78,
        "cost_overrun_lakh_cr": 5.66,
        "cost_overrun_pct": 15.2,
        "delayed_projects": 846,
        "delayed_pct": 42.6,
        "expenditure_lakh_cr": 21.82,
        "expenditure_ratio_pct": 51.0,
    },
    {
        "period": "2026-Q2",
        "label": "Jul 2026 (Latest Report)",
        "total_projects": 1775,
        "original_cost_lakh_cr": 32.18,
        "anticipated_cost_lakh_cr": 37.11,
        "cost_overrun_lakh_cr": 4.93,
        "cost_overrun_pct": 15.3,
        "delayed_projects": 756,
        "delayed_pct": 42.6,
        "expenditure_lakh_cr": 18.96,
        "expenditure_ratio_pct": 51.1,
    }
]

# Official Root Causes of Delay tracked by MoSPI/PAIMANA
PAIMANA_DELAY_REASONS: List[Dict[str, Any]] = [
    {
        "category": "Land Acquisition & Right of Way (RoW)",
        "percentage": 37.5,
        "affected_projects": 665,
        "avg_delay_months": 28.4,
        "description": "Compensation disputes, gazette notifications, private title litigation, and state revenue department handovers.",
        "icon": "LandPlot"
    },
    {
        "category": "Forest, Wildlife & Environment Clearances",
        "percentage": 23.8,
        "affected_projects": 422,
        "avg_delay_months": 22.1,
        "description": "Stage-I/II MoEF&CC statutory tree-felling permissions, compensatory afforestation land allotment (CAMPA), and National Green Tribunal stay orders.",
        "icon": "Trees"
    },
    {
        "category": "Contractor Default & Liquidity Distress",
        "percentage": 16.4,
        "affected_projects": 291,
        "avg_delay_months": 19.5,
        "description": "Slow contract mobilization, sub-contractor arbitration, raw material price escalation claims, and EPC re-tendering delays.",
        "icon": "Briefcase"
    },
    {
        "category": "Utility Shifting (Power, Telecom, Water)",
        "percentage": 12.2,
        "affected_projects": 216,
        "avg_delay_months": 14.8,
        "description": "Transco 400kV high-tension power line realignment, municipal water trunk line deviation, and railway siding bridge crossings.",
        "icon": "Zap"
    },
    {
        "category": "Scope Revision & Law and Order",
        "percentage": 10.1,
        "affected_projects": 179,
        "avg_delay_months": 16.2,
        "description": "Design alignment amendments, public protests, heavy monsoon flooding, and geological surprises in tunneling.",
        "icon": "ShieldCheck"
    },
]

# Sector-wise Historical Performance (PAIMANA Benchmark)
PAIMANA_SECTOR_HISTORICAL: List[Dict[str, Any]] = [
    {
        "sector": "Road Transport & Highways",
        "ministry": "Ministry of Road Transport and Highways (MoRTH)",
        "active_projects": 748,
        "anticipated_cost_lakh_cr": 14.28,
        "overrun_lakh_cr": 1.94,
        "overrun_pct": 15.7,
        "delayed_count": 312,
        "avg_delay_months": 18.2,
    },
    {
        "sector": "Railways",
        "ministry": "Ministry of Railways",
        "active_projects": 384,
        "anticipated_cost_lakh_cr": 9.45,
        "overrun_lakh_cr": 2.18,
        "overrun_pct": 30.0,
        "delayed_count": 210,
        "avg_delay_months": 36.5,
    },
    {
        "sector": "Petroleum & Natural Gas",
        "ministry": "Ministry of Petroleum and Natural Gas",
        "active_projects": 168,
        "anticipated_cost_lakh_cr": 5.12,
        "overrun_lakh_cr": 0.42,
        "overrun_pct": 8.9,
        "delayed_count": 68,
        "avg_delay_months": 14.0,
    },
    {
        "sector": "Power",
        "ministry": "Ministry of Power",
        "active_projects": 142,
        "anticipated_cost_lakh_cr": 4.60,
        "overrun_lakh_cr": 0.58,
        "overrun_pct": 14.4,
        "delayed_count": 58,
        "avg_delay_months": 24.8,
    },
    {
        "sector": "Coal",
        "ministry": "Ministry of Coal",
        "active_projects": 94,
        "anticipated_cost_lakh_cr": 1.48,
        "overrun_lakh_cr": 0.16,
        "overrun_pct": 12.1,
        "delayed_count": 34,
        "avg_delay_months": 16.4,
    },
    {
        "sector": "Urban Infrastructure / Metros",
        "ministry": "Ministry of Housing and Urban Affairs (MoHUA)",
        "active_projects": 82,
        "anticipated_cost_lakh_cr": 3.82,
        "overrun_lakh_cr": 0.31,
        "overrun_pct": 8.8,
        "delayed_count": 38,
        "avg_delay_months": 20.5,
    },
    {
        "sector": "Water Resources / Irrigation",
        "ministry": "Ministry of Jal Shakti",
        "active_projects": 46,
        "anticipated_cost_lakh_cr": 1.25,
        "overrun_lakh_cr": 0.28,
        "overrun_pct": 28.9,
        "delayed_count": 26,
        "avg_delay_months": 42.0,
    },
    {
        "sector": "Telecommunications",
        "ministry": "Ministry of Communications",
        "active_projects": 38,
        "anticipated_cost_lakh_cr": 0.88,
        "overrun_lakh_cr": 0.08,
        "overrun_pct": 10.0,
        "delayed_count": 10,
        "avg_delay_months": 12.5,
    },
]

def get_paimana_historical_payload():
    return {
        "time_series": PAIMANA_HISTORICAL_TRENDS,
        "delay_causes": PAIMANA_DELAY_REASONS,
        "sector_benchmarks": PAIMANA_SECTOR_HISTORICAL,
        "latest_snapshot": PAIMANA_HISTORICAL_TRENDS[-1],
    }
